/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSourceIdSeriesIdRouteImport } from './routes/series.$sourceId.$seriesId'
import { Route as SeriesSourceIdSeriesIdReadChapterIdRouteImport } from './routes/series.$sourceId.$seriesId.read.$chapterId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSourceIdSeriesIdRoute = SeriesSourceIdSeriesIdRouteImport.update({
  id: '/series/$sourceId/$seriesId',
  path: '/series/$sourceId/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSourceIdSeriesIdReadChapterIdRoute =
  SeriesSourceIdSeriesIdReadChapterIdRouteImport.update({
    id: '/read/$chapterId',
    path: '/read/$chapterId',
    getParentRoute: () => SeriesSourceIdSeriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/series/$sourceId/$seriesId': typeof SeriesSourceIdSeriesIdRouteWithChildren
  '/series/$sourceId/$seriesId/read/$chapterId': typeof SeriesSourceIdSeriesIdReadChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/series/$sourceId/$seriesId': typeof SeriesSourceIdSeriesIdRouteWithChildren
  '/series/$sourceId/$seriesId/read/$chapterId': typeof SeriesSourceIdSeriesIdReadChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/queue': typeof QueueRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/series/$sourceId/$seriesId': typeof SeriesSourceIdSeriesIdRouteWithChildren
  '/series/$sourceId/$seriesId/read/$chapterId': typeof SeriesSourceIdSeriesIdReadChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/notifications'
    | '/queue'
    | '/search'
    | '/settings'
    | '/series/$sourceId/$seriesId'
    | '/series/$sourceId/$seriesId/read/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/notifications'
    | '/queue'
    | '/search'
    | '/settings'
    | '/series/$sourceId/$seriesId'
    | '/series/$sourceId/$seriesId/read/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/notifications'
    | '/queue'
    | '/search'
    | '/settings'
    | '/series/$sourceId/$seriesId'
    | '/series/$sourceId/$seriesId/read/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  QueueRoute: typeof QueueRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SeriesSourceIdSeriesIdRoute: typeof SeriesSourceIdSeriesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$sourceId/$seriesId': {
      id: '/series/$sourceId/$seriesId'
      path: '/series/$sourceId/$seriesId'
      fullPath: '/series/$sourceId/$seriesId'
      preLoaderRoute: typeof SeriesSourceIdSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$sourceId/$seriesId/read/$chapterId': {
      id: '/series/$sourceId/$seriesId/read/$chapterId'
      path: '/read/$chapterId'
      fullPath: '/series/$sourceId/$seriesId/read/$chapterId'
      preLoaderRoute: typeof SeriesSourceIdSeriesIdReadChapterIdRouteImport
      parentRoute: typeof SeriesSourceIdSeriesIdRoute
    }
  }
}

interface SeriesSourceIdSeriesIdRouteChildren {
  SeriesSourceIdSeriesIdReadChapterIdRoute: typeof SeriesSourceIdSeriesIdReadChapterIdRoute
}

const SeriesSourceIdSeriesIdRouteChildren: SeriesSourceIdSeriesIdRouteChildren =
  {
    SeriesSourceIdSeriesIdReadChapterIdRoute:
      SeriesSourceIdSeriesIdReadChapterIdRoute,
  }

const SeriesSourceIdSeriesIdRouteWithChildren =
  SeriesSourceIdSeriesIdRoute._addFileChildren(
    SeriesSourceIdSeriesIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  QueueRoute: QueueRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SeriesSourceIdSeriesIdRoute: SeriesSourceIdSeriesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
